//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetail
    {
        public int id { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<int> Orderid { get; set; }
        public Nullable<int> Unitprice { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
